# Generated by Django 3.2 on 2021-04-24 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('legalities', models.JSONField()),
                ('art', models.URLField()),
                ('supertype', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='CardType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artifact', models.BooleanField()),
                ('conspiracy', models.BooleanField()),
                ('creature', models.BooleanField()),
                ('enchantment', models.BooleanField()),
                ('instant', models.BooleanField()),
                ('land', models.BooleanField()),
                ('phenomenon', models.BooleanField()),
                ('plane', models.BooleanField()),
                ('planeswalker', models.BooleanField()),
                ('scheme', models.BooleanField()),
                ('sorcery', models.BooleanField()),
                ('tribal', models.BooleanField()),
                ('vanguard', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ColorIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('red', models.BooleanField()),
                ('black', models.BooleanField()),
                ('white', models.BooleanField()),
                ('green', models.BooleanField()),
                ('blue', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Color Identities',
            },
        ),
        migrations.CreateModel(
            name='ConvertedManaCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('red', models.IntegerField()),
                ('black', models.IntegerField()),
                ('white', models.IntegerField()),
                ('green', models.IntegerField()),
                ('blue', models.IntegerField()),
                ('colorless', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Converted Mana Costs',
            },
        ),
    ]
